---
galaxy_info:
  role_name: node_exporter
  author: Maskanya
  description: Prometheus node_exporter bound to mesh interface
  license: MIT
  min_ansible_version: "2.14"
  platforms:
    - name: Ubuntu
      versions:
        - jammy
        - noble

dependencies: []
